[package]
name = "ddgemdespawn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ddcore-rs = { version = "0.3.5", features = ["memory"] }
soloud = "1"
